# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pwd',
            field=models.CharField(default='abcde', max_length=100),
        ),
    ]
